apiVersion: v1
kind: Service
metadata:
  name: startup-funding-service

spec:
  selector:
    app: startup-funding-app

  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501

  type: LoadBalancer